spring:
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5433/filerouge
    username: filerouge
    password: secret
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  # Liquibase Configuration
  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml

  # Email Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:your-email@gmail.com}
    password: ${EMAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:K19HxLUoJKxB6IJR9wOsOfK3K5JpQPWmBQTQfcxhCgY3O3E3HdfcFsFKpTFDYJa}
  token-validity-in-seconds: ${JWT_VALIDITY:86400}
  refresh-token-validity-in-seconds: ${JWT_REFRESH_VALIDITY:2592000}

# Server Configuration
server:
  port: 8080
  error:
    include-stacktrace: never

# Logging Configuration
logging:
  level:
    org.dev.filerouge: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.hibernate: INFO

# Application Configuration
application:
  email:
    sender-name: School Management System
    sender-email: ${EMAIL_USERNAME:your-email@gmail.com}
    admin-email: ${ADMIN_EMAIL:admin@your-school.com}